name: Daily Config Sync

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download config
        run: |
          for i in {1..3}; do
            curl -f -o lazy_group.conf https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/lazy_group.conf && break
            sleep 5
          done
          
      - name: Modify config
        run: |
          sed -i 's@^GEOIP,CN,DIRECT@RULE-SET,https://raw.githubusercontent.com/ACL4SSR0/custom_rules/refs/heads/main/custom.list,DIRECT\nGEOIP,CN,DIRECT@g' lazy_group.conf
          sed -i 's@ipv6 = true@ipv6 = false@g' lazy_group.conf
      - name: Debug remote URL
        run: git remote -v

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add lazy_group.conf
          git commit -m "Auto update config [skip ci]" || echo "No changes to commit"
          git push origin main
