name: Daily Config Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download config
        run: |
          for i in {1..3}; do
            curl -f -o lazy_group.conf https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/lazy_group.conf && break
            sleep 5
          done
          
      - name: Modify config
        run: |
          sed -i 's/^GEOIP,CN,DIRECT/IP-CIDR6,::\/0,DIRECT,no-resolve\nGEOIP,CN,DIRECT/g' lazy_group.conf

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add lazy_group.conf
          git commit -m "Auto update config [skip ci]" || echo "No changes to commit"
          git push origin main
